config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "comments#index"
  get 'index' => 'comments#index'
  resources :comments
  resources :replies
  resources :projects
  resources :project_relations
  resources :categories
  resources :vessels
  resource :dashboards
end

app/models/project_relation.rb
class ProjectRelation < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/project_relations_controller.rb
class ProjectRelationsController < ApplicationController
  before_action :set_project_relation, only: %i[ show edit update destroy ]

  def index
    @project_relations = ProjectRelation.all
  end

  def show
  end

  def new
    @project_relation = ProjectRelation.new
    @project_options = Project.all.map{ |u| [ u.reference, u.id ]}.uniq { |x| x[0] }
    @user_options = User.all.map{ |u| [ u.username, u.id ]}.uniq { |x| x[0] }
  end

  def edit
    @project_options = Project.all.map{ |u| [ u.reference, u.id ]}.uniq { |x| x[0] }
    @user_options = User.all.map{ |u| [ u.username, u.id ]}.uniq { |x| x[0] }
  end

  def create
    @project_relation = ProjectRelation.new(project_relation_params)
    if @project_relation.save
      redirect_to @project_relation
    else
      render :new
    end
  end

  def update
    if @project_relation.update(project_relation_params)
      redirect_to @project_relation
    else
      render :edit
    end
  end

  def destroy
    @project_relation.destroy
  end

  private
    def set_project_relation
      @project_relation = ProjectRelation.find(params[:id])
    end

    def project_relation_params
      params.require(:project_relation).permit(:user_id, :project_id)
    end
end

app/helpers/project_relations_helper.rb
module ProjectRelationsHelper
end

app/views/project_relations/_form.html.erb
<%= simple_form_for(@project_relation) do |f| %>
<%= f.error_notification %>
<%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>
<div class="field">
  <div class="control">
    <div><%= f.input :project_id, label: "Project", input_html: { class: "select" }, collection: @project_options, wrapper: false, label_html: {class: "label"}, placeholder: "Project", autofocus: false %></div><br>
    <div><%= f.input :user_id, label: "User", input_html: { class: "select" }, collection: @user_options, wrapper: false, label_html: {class: "label"}, placeholder: "User", autofocus: false %></div><br>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/project_relations/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Project Attribution</h1>
				<%= render 'form', project_relation: @project_relation, project_options: @project_options, user_options: @user_options %><br>
				<%= link_to 'Cancel', project_relations_path, class: "button is-dark" %>
			</div>
		</div>
	</div>
</div>

app/views/project_relations/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Id</th> 
      <th>Project</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_relations.each do |project_relation| %>
      <tr>
        <td><%= link_to project_relation.id, project_relation %></td>
        <td><%= project_relation.project.reference %></td>
        <td><%= project_relation.user.username %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Project Attribution', new_project_relation_path(project_relation: @project_relation) %>

app/views/project_relations/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">New Project Attribution</h1>
				<%= render 'form', project_relation: @project_relation, project_options: @project_options, user_options: @user_options %><br>
        <%= link_to 'Back', project_relations_path, class: "button is-dark" %>
			</div>
		</div>
	</div>
</div>

app/views/project_relations/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Id</th> 
      <th>Project</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @project_relation.id %></td>
      <td><%= @project_relation.project.reference %></td>
      <td><%= @project_relation.user.username %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_project_relation_path(@project_relation) %> |
<%= link_to 'Back', project_relations_path %>