config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "comments#index"
  get 'index' => 'comments#index'
  resources :comments
  resources :replies
  resources :projects
  resources :project_relations
  resources :categories
  resources :vessels
  resource :dashboards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :category
  belongs_to :vessel
  has_many :replies, dependent: :delete_all
  has_one_attached :image, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_relations
  has_many :users, through: :project_relations
  has_many :comments
  has_many :vessels
end

app/models/project_relation.rb
class ProjectRelation < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  has_one_attached :image, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :project_relations
  has_many :comments
  has_many :replies
  has_many :projects, through: :project_relations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vessel.rb
class Vessel < ApplicationRecord
  belongs_to :project
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:reference, :name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :set_project_options, only: %i[ index new edit ]
  before_action :set_vessel_options, only: %i[ index new edit ]
  before_action :set_category_options, only: %i[ index new edit ]

  def index
    if params[:selected_project].present?
      @comments = Comment.where(project_id: params[:selected_project].to_i)
    else
      @comments = Comment.where(project_id: current_user.projects.map{ |u| u.id})
    end
  end

  def show
    @replies = @comment.replies
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to @comment
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to @comment
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_project_options
      @project_options = current_user.projects.map{ |u| [ u.reference, u.id ]}.uniq { |x| x[0] }
    end

    def set_vessel_options
      @vessel_options = Vessel.where(project_id: current_user.projects.map{ |u| u.id}).map{ |u| [ u.hull_number, u.id ]}.uniq { |x| x[0] }
    end

    def set_category_options
      @category_options = Category.all
    end

    def comment_params
      params.require(:comment).permit(:title, :body, :user_id, :project_id, :category_id, :status, :closing_date, :vessel_id, :image)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_comments
  before_action :set_project_options
  before_action :set_vessel_options
  before_action :set_category_options

  def show
    #@process_group_by_dates = @comments.group(:status).group_by_day(:created_at).count
    @process_group_by_dates = @comments.group_by_day(:created_at).count
    sum = 0
    @process_group_by_dates = @process_group_by_dates.each { |k, v| @process_group_by_dates[k] = (sum = sum + v)}
  end

  private
  def set_comments
    @comments = Comment.where(project_id: current_user.projects.map{ |u| u.id})
  end

  def set_project_options
    @project_options = current_user.projects.map{ |u| [ u.reference, u.id ]}.uniq { |x| x[0] }
  end

  def set_vessel_options
    @vessel_options = Vessel.where(project_id: current_user.projects.map{ |u| u.id}).map{ |u| [ u.hull_number, u.id ]}.uniq { |x| x[0] }
  end

  def set_category_options
    @category_options = Category.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  def index
    @projects = Project.all
  end

  def show
    @users = @project.users
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:reference)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def new
    @comment = Comment.find(params[:comment].to_i)
    @reply = Reply.new
  end

  def create
    @reply = Reply.new(reply_params)
    if @reply.save
      redirect_to @reply.comment
    else
      render :new
    end
  end

  private
    def reply_params
      params.require(:reply).permit(:body, :user_id, :comment_id, :image)
    end
end

app/controllers/vessels_controller.rb
class VesselsController < ApplicationController
  before_action :set_vessel, only: %i[ show edit update destroy ]
  before_action :set_project_options, only: %i[ index new edit ]

  def index
    @vessels = Vessel.where(project_id: current_user.projects.map{ |u| u.id})
  end

  def show
  end

  def new
    @vessel = Vessel.new
  end

  def edit
  end

  def create
    @vessel = Vessel.new(vessel_params)
    if @vessel.save
      redirect_to @vessel
    else
      render :new
    end
  end

  def update
    if @vessel.update(vessel_params)
      redirect_to @vessel
    else
      render :edit
    end
  end

  def destroy
    @vessel.destroy
  end

  private
    def set_vessel
      @vessel = Vessel.find(params[:id])
    end

    def set_project_options
      @project_options = current_user.projects.map{ |u| [ u.reference, u.id ]}.uniq { |x| x[0] }
    end

    def vessel_params
      params.require(:vessel).permit(:project_id, :hull_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/project_relations_helper.rb
module ProjectRelationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
<%= f.error_notification %>
<%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>
<div class="field">
  <div class="control">
    <div><%= f.input :reference, label: "Category Reference", input_html: { class: "text" }, wrapper: false, label_html: {class: "label"}, placeholder: "Reference", autofocus: true %></div><br>
    <div><%= f.input :name, label: "Category Name", input_html: { class: "text" }, wrapper: false, label_html: {class: "label"}, placeholder: "Name", autofocus: false %></div><br>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/categories/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Category</h1>
				<%= render 'form', category: @category %><br>
				<%= link_to 'Cancel', categories_path, class: "button is-dark" %>
			</div>
		</div>
	</div>
</div>

app/views/categories/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Id</th> 
      <th>Reference</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category %></td>
        <td><%= category.reference %></td>
        <td><%= category.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Category', new_category_path(category: @category) %>

app/views/categories/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">New Category Attribution</h1>
				<%= render 'form', category: @category %><br>
        <%= link_to 'Back', categories_path, class: "button is-dark" %>
			</div>
		</div>
	</div>
</div>

app/views/categories/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Id</th> 
      <th>Reference</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= link_to @category.id, @category %></td>
      <td><%= @category.reference %></td>
      <td><%= @category.name %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
<%= f.error_notification %>
<%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>
<div class="field">
  <div class="control">
    <div><%= f.input :project_id, label: "Project", input_html: { class: "select" }, collection: @project_options, wrapper: false, label_html: {class: "label"}, placeholder: "Project", autofocus: false %></div><br>
    <div><%= f.input :vessel_id, label: "Vessel", input_html: { class: "select" }, collection: @vessel_options, wrapper: false, label_html: {class: "label"}, placeholder: "Vessel", autofocus: false %></div><br>
    <div><%= f.input :category_id, label: "Category", input_html: { class: "select" }, collection: @category_options, wrapper: false, label_html: {class: "label"}, placeholder: "Category", autofocus: false %></div><br>
    <div><%= f.input :title, label: "Comment Title", input_html: { class: "text" }, wrapper: false, label_html: {class: "label"}, placeholder: "Comment title", autofocus: true %></div><br>
    <div><%= f.input :body, label: "Comment Description", input_html: { class: "text" }, wrapper: false, label_html: {class: "label"}, placeholder: "Comment description", autofocus: false %></div>
    <div><%= f.input :image, label: "Attachment", input_html: { class: "file" }, wrapper: false, label_html: {class: "label"}, autofocus: false %></div>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/comments/_searchform.html.erb
<%= form_with url: "/index", method: :get do |form| %>
  <div class="field">
    <%= form.label :project %><br>
    <%= select_tag(:selected_project, options_for_select(@project_options)) %>
  </div>

  <div class="actions">
    <%= form.submit "Search" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Comment</h1>
				<%= render 'form', comment: @comment, project_options: @project_options, category_options: @category_options  %><br>
				<%= link_to 'Cancel', comments_path, class: "button is-dark" %>
			</div>
		</div>
	</div>
</div>

app/views/comments/index.html.erb
<%= render 'searchform', project_options: @project_options %>

<table class="table">
  <thead>
    <tr>
      <th>Id</th> 
      <th>Project</th>
      <th>Vessel</th>
      <th>Category</th>
      <th>Issued by</th>
      <th>Status</th>
      <th>Creation date</th>
      <th>Closing date</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to comment.id, comment %></td>
        <td><%= comment.project.reference %></td>
        <td><%= comment.vessel.nil? ? nil : comment.vessel.hull_number %></td>
        <td><%= comment.category.reference %></td>
        <td><%= comment.user.username %></td>
        <td><%= comment.status ? 'Closed' : 'Open' %></td>
        <td><%= comment.created_at.strftime("%d/%m/%Y") %></td>
        <td><%= comment.closing_date.nil? ? nil : comment.closing_date.strftime("%d/%m/%Y") %></td>
        <td><%= comment.title %></td>
        <td><%= comment.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Comment', new_comment_path(comment: @comment) %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment, project_options: @project_options %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Id</th> 
      <th>Project</th>
      <th>Vessel</th>
      <th>Category</th>
      <th>Issued by</th>
      <th>Status</th>
      <th>Creation date</th>
      <th>Closing date</th>
      <th>Title</th>
      <th>Description</th>
      <th>Attachment</th>
      <th colspan="11"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @comment.id %></td>
      <td><%= @comment.project.reference %></td>
      <td><%= @comment.vessel.nil? ? nil : @comment.vessel.hull_number %></td>
      <td><%= @comment.category.reference %></td>
      <td><%= @comment.user.username %></td>
      <td><%= @comment.status ? 'Closed' : 'Open' %></td>
      <td><%= @comment.created_at.strftime("%d/%m/%Y") %></td>
      <td><%= @comment.closing_date.nil? ? nil : @comment.closing_date.strftime("%d/%m/%Y") %></td>
      <td><%= @comment.title %></td>
      <td><%= @comment.body %></td>
      <td><%= @comment.image.present? ? link_to('Click', rails_blob_path(@comment.image, disposition: "attachment")) : 'N/A' %></td>
    </tr>
  </tbody>
</table>

<% unless @replies.empty? %>
  <table class="table">
    <thead>
      <tr>
        <th>Iteration</th> 
        <th>Issued by</th>
        <th>Remark</th>
        <th>Attachment</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @replies.each_with_index do |reply, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= reply.user.username %></td>
          <td><%= reply.body %></td>
          <td><%= reply.image.present? ? link_to('Click', rails_blob_path(reply.image, disposition: "attachment")) : 'N/A' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if @comment.status %>
  <%= link_to('Open Comment', comment_path(@comment, comment: {status: false, closing_date: nil}), method: :put, confirm: "Are you sure?", class: "button is-dark")  %>
<% else %>
  <%= link_to('Close Comment', comment_path(@comment, comment: {status: true, closing_date: DateTime.now}), method: :put, confirm: "Are you sure?", class: "button is-dark")  %>
<% end %>

<%= link_to 'New Reply', new_reply_path(comment: @comment), class: "button is-dark"  %>
<%= link_to 'Edit', edit_comment_path(@comment), class: "button is-dark"  %>
<%= link_to 'Back', comments_path, class: "button is-dark"  %>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
<%= f.error_notification %>
<%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>
<div class="field">
  <div class="control">
    <div><%= f.input :reference, label: "Project Reference", input_html: { class: "text" }, wrapper: false, label_html: {class: "label"}, placeholder: "Project Reference", autofocus: true %></div><br>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/projects/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Project</h1>
				<%= render 'form', project: @project %><br>
				<%= link_to 'Cancel', projects_path, class: "button is-dark" %>
			</div>
		</div>
	</div>
</div>

app/views/projects/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Id</th> 
      <th>Reference</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, project %></td>
        <td><%= project.reference %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Project', new_project_path(project: @project) %> |
<%= link_to 'Back', comments_path %>

app/views/projects/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">New Project</h1>
				<%= render 'form', project: @project %><br>
        <%= link_to 'Back', projects_path, class: "button is-dark" %>
			</div>
		</div>
	</div>
</div>

app/views/projects/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Id</th> 
      <th>Reference</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @project.id %></td>
      <td><%= @project.reference %></td>
    </tr>
  </tbody>
</table>

<% unless @users.empty? %>
  <table class="table">
    <thead>
      <tr>
        <th>Id</th> 
        <th>User</th> 
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each_with_index do |user, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= user.username %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'New Project attribution', new_project_relation_path(project: @project) %> |
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/replies/_form.html.erb
<%= simple_form_for(@reply) do |f| %>
<%= f.error_notification %>
<%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>
<div class="field">
  <div class="control">
    <div><%= f.input :body, label: "Remark", input_html: { class: "text" }, wrapper: false, label_html: {class: "label"}, placeholder: "Remark", autofocus: false %></div>
    <div><%= f.input :image, label: "Attachment", input_html: { class: "file" }, wrapper: false, label_html: {class: "label"}, autofocus: false %></div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :comment_id, value: @comment.id %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/replies/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">New Reply</h1>
				<%= render 'form', reply: @reply, comment: @comment %><br>
        <%= link_to 'Back', @comment, class: "button is-dark" %>
			</div>
		</div>
	</div>
</div>

app/views/vessels/_form.html.erb
<%= simple_form_for(@vessel) do |f| %>
<%= f.error_notification %>
<%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>
<div class="field">
  <div class="control">
    <div><%= f.input :project_id, label: "Project", input_html: { class: "select" }, collection: @project_options, wrapper: false, label_html: {class: "label"}, placeholder: "Project", autofocus: false %></div><br>
    <div><%= f.input :hull_number, label: "Hull Number", input_html: { class: "text" }, wrapper: false, label_html: {class: "label"}, placeholder: "Hull Number", autofocus: true %></div><br>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/vessels/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Vessel</h1>
				<%= render 'form', vessel: @vessel %><br>
				<%= link_to 'Cancel', vessels_path, class: "button is-dark" %>
			</div>
		</div>
	</div>
</div>

app/views/vessels/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Id</th> 
      <th>Project</th>
      <th>Hull Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vessels.each do |vessel| %>
      <tr>
        <td><%= link_to vessel.id, vessel %></td>
        <td><%= vessel.project.reference %></td>
        <td><%= vessel.hull_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Vessel', new_vessel_path(vessel: @vessel) %> |
<%= link_to 'Back', comments_path %>

app/views/vessels/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">New Vessel</h1>
				<%= render 'form', vessel: @vessel %><br>
        <%= link_to 'Back', vessels_path, class: "button is-dark" %>
			</div>
		</div>
	</div>
</div>

app/views/vessels/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Id</th> 
      <th>Project</th>
      <th>Hull Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @vessel.id %></td>
      <td><%= @vessel.project.reference %></td>
      <td><%= @vessel.hull_number %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_vessel_path(@vessel) %> |
<%= link_to 'Back', vessels_path %>