config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "comments#index"
  get 'index' => 'comments#index'
  resources :comments
  resources :replies
  resources :projects
  resources :project_relations
  resources :categories
  resources :vessels
  resource :dashboards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :category
  belongs_to :vessel
  has_many :replies, dependent: :delete_all
  has_one_attached :image, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_relations
  has_many :users, through: :project_relations
  has_many :comments
  has_many :vessels
end

app/models/project_relation.rb
class ProjectRelation < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  has_one_attached :image, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :project_relations
  has_many :comments
  has_many :replies
  has_many :projects, through: :project_relations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vessel.rb
class Vessel < ApplicationRecord
  belongs_to :project
  has_many :comments
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :set_project_options, only: %i[ index new edit ]
  before_action :set_vessel_options, only: %i[ index new edit ]
  before_action :set_category_options, only: %i[ index new edit ]

  def index
    if params[:selected_project].present?
      @comments = Comment.where(project_id: params[:selected_project].to_i)
    else
      @comments = Comment.where(project_id: current_user.projects.map{ |u| u.id})
    end
  end

  def show
    @replies = @comment.replies
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to @comment
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to @comment
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_project_options
      @project_options = current_user.projects.map{ |u| [ u.reference, u.id ]}.uniq { |x| x[0] }
    end

    def set_vessel_options
      @vessel_options = Vessel.where(project_id: current_user.projects.map{ |u| u.id}).map{ |u| [ u.hull_number, u.id ]}.uniq { |x| x[0] }
    end

    def set_category_options
      @category_options = Category.all
    end

    def comment_params
      params.require(:comment).permit(:title, :body, :user_id, :project_id, :category_id, :status, :closing_date, :vessel_id, :image)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  def index
    @projects = Project.all
  end

  def show
    @users = @project.users
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:reference)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def new
    @comment = Comment.find(params[:comment].to_i)
    @reply = Reply.new
  end

  def create
    @reply = Reply.new(reply_params)
    if @reply.save
      redirect_to @reply.comment
    else
      render :new
    end
  end

  private
    def reply_params
      params.require(:reply).permit(:body, :user_id, :comment_id, :image)
    end
end

app/controllers/vessels_controller.rb
class VesselsController < ApplicationController
  before_action :set_vessel, only: %i[ show edit update destroy ]
  before_action :set_project_options, only: %i[ index new edit ]

  def index
    @vessels = Vessel.where(project_id: current_user.projects.map{ |u| u.id})
  end

  def show
  end

  def new
    @vessel = Vessel.new
  end

  def edit
  end

  def create
    @vessel = Vessel.new(vessel_params)
    if @vessel.save
      redirect_to @vessel
    else
      render :new
    end
  end

  def update
    if @vessel.update(vessel_params)
      redirect_to @vessel
    else
      render :edit
    end
  end

  def destroy
    @vessel.destroy
  end

  private
    def set_vessel
      @vessel = Vessel.find(params[:id])
    end

    def set_project_options
      @project_options = current_user.projects.map{ |u| [ u.reference, u.id ]}.uniq { |x| x[0] }
    end

    def vessel_params
      params.require(:vessel).permit(:project_id, :hull_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/project_relations_helper.rb
module ProjectRelationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Owner Comment Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Owner Comment Manager</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
        <div id="navbarExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'Comments', comments_path, class: "button is-info is-inverted" %>
              </p>
              <p class="control">
                <%= link_to 'Projects', projects_path, class: "button is-info is-inverted" %>
              </p>
              <p class="control">
                <%= link_to 'Attributions', project_relations_path, class: "button is-info is-inverted" %>
              </p>
              <p class="control">
                <%= link_to 'Categories', categories_path, class: "button is-info is-inverted" %>
              </p>
              <p class="control">
                <%= link_to 'Vessels', vessels_path, class: "button is-info is-inverted" %>
              </p>
              <p class="control">
                <%= link_to 'Dashboard', dashboards_path, class: "button is-info is-inverted" %>
              </p>
              <% if user_signed_in? %>
                <p class="control">
                  <%= link_to current_user.username, edit_user_registration_path, class: "button is-info" %>
                </p>
                <p>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %>
                </p>
              <% else %>
              <p class="control">
                <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
              </p>
              <% end %>
            </div>
          </div>
        </div>

    </nav>

    <%= yield %>
  </body>
</html>